# Generated by Django 5.2 on 2025-05-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
